#!/bin/bash

./configure --disable-gpl --disable-static --enable-shared --enable-libmp3lame --enable-version3 --enable-zlib --enable-libvorbis --enable-libtheora --enable-libopenjpeg --disable-w32threads --enable-bzlib --extra-cflags=-DPTW32_STATIC_LIB --enable-libvpx --disable-decoder=prores --disable-encoder=prores --disable-decoder=eacmv --disable-decoder=eamad --disable-decoder=eatgq --disable-decoder=eatgv --disable-decoder=eatqi --disable-decoder=bethsoftvid --disable-demuxer=aac --disable-parser=dvdsub --disable-decoder=dvdsub --disable-decoder=prores_lgpl --prefix=$HOME/fflibs64 --enable-iconv --extra-libs=-lstdc++ --extra-libs=-lpng --extra-ldflags=-L/usr/local/lib --enable-runtime-cpudetect --extra-cflags=-I/usr/local/include --disable-sdl


make
make install
